### PR TITLE
Feature/issue 366

### PR DESCRIPTION
**Pull request by romanstetsyk**
# Description

Current behavior: when the calendar is opened all events from the database are fetched.
New behavior: events are loaded only for the current month. If you move to the next/previous month a new request to the backend is made for that month. Events are added to the state, so no new request is made if you switch back.

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires an update to testing

## Issue

- [x] Is this related to a specific issue? If so, please specify: #366 

# Checklist:

- [x] This PR is up to date with the main branch, and merge conflicts have been resolved
- [x] I have executed `npm run test` and all tests have passed successfully or I have included details within my PR on the failure.
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by romanstetsyk** [comment]
Requesting a code review

**Comment by Caleb-Cohen** [comment]
Events are added to the state, so no new request is made if you switch back.

Great implementation there.

Why the choice to only load new events on calendar scrolls instead of loading the rest of the events once the initial page has been rendered?

**Comment by romanstetsyk** [comment]
I tried this approach using a second `useEffect` with `setTimeout`, but it doesn't work well with a slow internet connection, especially if you switch months before events are loaded. Loading all events from the database at once sometimes takes a few seconds, causing a re-render after a few seconds.

**Comment by Caleb-Cohen** [comment]
> I tried this approach using a second `useEffect` with `setTimeout`, but it doesn't work well with a slow internet connection, especially if you switch months before events are loaded. Loading all events from the database at once sometimes takes a few seconds, causing a re-render after a few seconds.

Makes sense. Also assuming we're still here in 12 months, what's the value in loading the previous 12 months of events?

**Comment by romanstetsyk** [comment]
Another approach I considered was loading only the fields that are visible in the calendar (start time, title). Then if a user opens an event, make a new API call to the `getOne` endpoint.

In any way, there was a notable improvement in loading time only after I populated the database with thousands of events. So I guess it's not critical at this point :)

**Comment by romanstetsyk** [comment]
> what's the value in loading the previous 12 months of events?
I use MongoDB atlas for this, not a local db. It sometimes takes ~5 seconds, and sometimes it's instantly.

**Comment by Caleb-Cohen** [comment]
LGTM! Still waiting on @MatthewBozin to review.

**Review by Caleb-Cohen — APPROVED** [review]

**Review by MatthewBozin — APPROVED** [review]

**Pull request merged**
