### PR TITLE
fixed 401: duplicate events in state hook

### PR DESCRIPTION
**Pull request by romanstetsyk**
# Description

This PR prevents adding duplicate events to the state if a recurring event spans more than 1 month.

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires an update to testing

## Issue

- [x] Is this related to a specific issue? If so, please specify: #401 

# Checklist:

- [x] This PR is up to date with the main branch, and merge conflicts have been resolved
- [x] I have executed `npm run test` and all tests have passed successfully or I have included details within my PR on the failure.
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Caleb-Cohen** [comment]
LGTM, should we add testing to accompany this?

**Comment by Caleb-Cohen** [comment]
Howdy @romanstetsyk did you get a chance to review my question?

**Comment by romanstetsyk** [comment]
@Caleb-Cohen I'm sorry, I didn't see your last message. It's a good idea, but I still need to figure out how to write tests in Cypress. It would be great if someone could add tests to this pr or create a separate issue

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen I'm sorry, I didn't see your last message. It's a good idea, but I still need to figure out how to write tests in Cypress. It would be great if someone could add tests to this pr or create a separate issue

I'll take it up!

**Pull request merged**
