### PR TITLE
Feature/admin dashboard visualize group events 413

### PR DESCRIPTION
**Pull request by cblanken**
# Description

Group repeating events with the same `groupId` into a single items on the admin dashboard and split single (non-repeating) events and repeating events into separate sections.

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] This change requires an update to testing

## Issue
This PR addresses issue #413 
- [x] Is this related to a specific issue? If so, please specify:

# Checklist:

- [x] This PR is up to date with the main branch, and merge conflicts have been resolved
- [x] I have executed `npm run test` and all tests have passed successfully or I have included details within my PR on the failure.
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by cblanken** [comment]
Here are a few screenshots

Admin Dashboard with 1 single event and 1 recurring event.
image

Recurring event on calender
image

**Review by Caleb-Cohen — COMMENTED** [review]
Just curious why this was added. Did we not have this functionality? 

Otherwise, LGTM

**Comment by cblanken** [comment]
> 

Before, repeating events were rendered individually for each instance.
According to issue #413 it was requested to group recurring events into individual items which this PR addresses.

**Comment by Caleb-Cohen** [comment]
> > Just curious why this was added. Did we not have this functionality?
> > Otherwise, LGTM
> 
> Before, repeating events were rendered individually for each instance. According to issue #413 it was requested to group recurring events into individual items which this PR addresses.

Sorry I was referencing a code block that didn't carry over to the comment. I'm specifically addressing the functions added to `cypress/support/commands.js`

```

Cypress.Commands.add("deleteOwnEvent", id => {
  if (id) {
    cy.request("DELETE", `/events/${id}`);
  }
});

Cypress.Commands.add("getAllEvents", userCode => {
  // cy.login(userCode)
  return cy.request("GET", "/events");
});

```

**Comment by cblanken** [comment]
Not that I could find. There were only Cypress commands for `login`, `createOwnEvents`, and `deleteOwnGroupEvents`, so I added those to avoid a bunch of code duplication in the tests.

**Pull request merged**
