### PR TITLE
react router added

### PR DESCRIPTION
**Pull request by mandliyarajendra11**
issue solve-Convert Together to React Router #404

### CODE REVIEW

**Comment by Caleb-Cohen** [comment]
Is this ready for review? I'm hitting compile errors in local and with github tests.

**Comment by mandliyarajendra11** [comment]
which type of error you get sir ?  please send screenshot

**Comment by Caleb-Cohen** [comment]
Hey there @mandliyarajendra11 just checking in on this, thanks!

**Comment by mandliyarajendra11** [comment]
Sorry sir, I forgot. Let me check.

**Pull request closed without merging**
